---
configs: {}
networks: {}
secrets:
  key:
    external: true
services:
  batfish:
    container_name: thing-batfish
    hostname: thing-batfish
    image: docker.io/batfish/allinone:latest
    ports:
    - 8888:8888
    - 9997:9997
    - 9996:9996
    volumes:
    - batfish-data-compose:/data
  mongo:
    container_name: thing-mongo
    environment:
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_USERNAME: root
    hostname: thing-mongo
    image: docker.io/library/mongo:8.0.3
    ports:
    - 27017:27017
    volumes:
    - mongo-data-db-compose:/data/db
    - mongo-data-configdb-compose:/data/configdb
  mongo-express:
    container_name: thing-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_SERVER: thing-mongo
    hostname: thing-mongo-express
    image: docker.io/library/mongo-express:1.0.2
    ports:
    - 8181:8081
volumes:
  batfish-data-compose: null
  mongo-data-configdb-compose: null
  mongo-data-db-compose: null
